### ISSUE TITLE
The mapping thread need depth supervision, where can I find the monocular mapping?

### ISSUE THREAD

**Issue by thua919** [youmi-zym/GO-SLAM#25]
Hi!

Thank you so much for the open-source code.

I am wondering, is the class Mapper() still only developed for the **a posed RGB-D input**? because I only find the mapping code with depth supervision.

Looking forward to your kind reply!

**Comment by youmi-zym** [comment]
Hi,

For the mapping thread, it collects depth and pose from the tracking thread, as you can see [here](https://github.com/youmi-zym/GO-SLAM/blob/main/src/mapping.py#L175C52-L175C52). 

That means, for the tracking thread, it works in mono, rgbd, and stereo mode. No matter which mode it works in, it predicts pose and depth for each keyframe and sends them to the mapping thread for rendering.

Best,
Youmin

**Comment by thua919** [comment]
Thank you so much for the speedy reply ; )

In this case, I am wondering why not use the sensor depth for RGB-D mode? 
Also, I am wondering, how synchronise is the mapping thread? Can it support, for instance, more iterations for higher-mapping fidelity by caching the data stream provided by tracker?

**Comment by youmi-zym** [comment]
Hi, 

Our tracking thread will optimize the depth even in RGB-D mode. So, with improved depth, the mapping thread could get better results.

The mapping thread runs at a very high frequency. We set a few iterations because we hope the mapping thread could update the geometry of the scene ASAP. But yes, more iterations might lead to a higher mapping fidelity. 

Best,
Youmin
